spring.application.name=cookshare

# Datenbank
spring.datasource.url=jdbc:mysql://localhost:3306/cookshare
spring.datasource.username=${DB_USER:?DB_USER fehlt}
spring.datasource.password=${DB_PASS:?DB_PASS fehlt}
spring.jpa.hibernate.ddl-auto=update

# Bilder speichern
app.upload-dir=./uploads

# E-Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:?MAIL_USER fehlt}
spring.mail.password=${MAIL_APP_PASS:?MAIL_APP_PASS fehlt}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
app.jwtSecret=${JWT_SECRET:?JWT_SECRET fehlt}

# DEBUG Einstellungen
logging.level.root=INFO
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n